export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_BLOG_START = "DELETE_BLOG_START";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";

export const UPDATE_BLOG = "UPDATE_BLOG";
export const UPDATE_BLOG_START = "UPDATE_BLOG_START";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";

export const GET_BLOG_LIST = "GET_BLOG_LIST";
export const GET_BLOG_LIST_START = "GET_BLOG_LIST_START";
export const GET_BLOG_LIST_FAIL = "GET_BLOG_LIST_FAIL";
export const GET_BLOG_LIST_SUCCESS = "GET_BLOG_LIST_SUCCESS";

export const GET_ONE_BLOG = "GET_ONE_BLOG";
export const GET_ONE_BLOG_START = "GET_ONE_BLOG_START";
export const GET_ONE_BLOG_FAIL = "GET_ONE_BLOG_FAIL";
export const GET_ONE_BLOG_SUCCESS = "GET_ONE_BLOG_SUCCESS";

export const POST_BLOG = "POST_BLOG";
export const POST_BLOG_START = "POST_BLOG_START";
export const POST_BLOG_FAIL = "POST_BLOG_FAIL";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
