export const GET_BLOG_LIST = "GET_BLOG_LIST";
export const GET_BLOG_LIST_START = "GET_BLOG_LIST_START";
export const GET_BLOG_LIST_FAIL = "GET_BLOG_LIST_FAIL";
export const GET_BLOG_LIST_SUCCESS = "GET_BLOG_LIST_SUCCESS";
